import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#613453',
        'on-primary': '#ffffff',
        'primary-container': '#7b4b6b',
        'on-primary-container': '#fec0e6',
        'primary-fixed': '#ffd8ee',
        'primary-fixed-dim': '#f1b5da',
        'on-primary-fixed': '#330c29',
        secondary: '#73575e',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffd9e1',
        'on-secondary-container': '#795d64',
        'secondary-fixed': '#ffd9e1',
        'secondary-fixed-dim': '#e1bdc5',
        tertiary: '#623730',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#7d4e46',
        'on-tertiary-container': '#ffc4ba',
        'tertiary-fixed': '#ffdad4',
        'tertiary-fixed-dim': '#f6b8ad',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#fff7f9',
        'on-surface': '#1e1a1d',
        'surface-variant': '#e9e0e3',
        'on-surface-variant': '#4f444a',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#faf1f4',
        'surface-container': '#f5ecef',
        'surface-container-high': '#efe6e9',
        'surface-container-highest': '#e9e0e3',
        'surface-dim': '#e0d8db',
        'surface-bright': '#fff7f9',
        'surface-tint': '#7f4f6f',
        outline: '#81737a',
        'outline-variant': '#d2c2ca',
        background: '#fff7f9',
        'on-background': '#1e1a1d',
        'inverse-surface': '#342f32',
        'inverse-on-surface': '#f8eef2',
        'inverse-primary': '#f1b5da',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['"Roboto Flex"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-400px 0' },
          '100%': { backgroundPosition: '400px 0' },
        },
        pulseBorder: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.4' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-8px)' },
          '40%': { transform: 'translateX(8px)' },
          '60%': { transform: 'translateX(-6px)' },
          '80%': { transform: 'translateX(6px)' },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '0.5' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        countUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        shimmer: 'shimmer 1.6s ease-in-out infinite',
        'pulse-border': 'pulseBorder 2s ease-in-out infinite',
        shake: 'shake 0.4s ease-in-out',
        ripple: 'ripple 0.5s linear forwards',
        'count-up': 'countUp 0.3s ease-out forwards',
      },
    },
  },
  plugins: [forms({ strategy: 'class' })],
} satisfies Config;
